// Brazilian Fauna Avatars
// SVG placeholders - replace with actual Brazilian fauna-inspired SVG icons

export const BRAZILIAN_FAUNA_AVATARS = [
  {
    id: 'jaguar',
    name: 'Onça-Pintada',
    nameEn: 'Jaguar',
    namePt: 'Onça-Pintada',
    taglineEn: 'Fierce Guardian of the Amazon',
    taglinePt: 'Guardião Feroz da Amazônia',
    emoji: '🐆',
    // svg: '<svg>...</svg>' // TODO: Replace with actual SVG
  },
  {
    id: 'toucan',
    name: 'Tucano',
    nameEn: 'Toucan',
    namePt: 'Tucano',
    taglineEn: 'Colorful Spirit of the Rainforest',
    taglinePt: 'Espírito Colorido da Floresta',
    emoji: '🦜',
  },
  {
    id: 'capybara',
    name: 'Capivara',
    nameEn: 'Capybara',
    namePt: 'Capivara',
    taglineEn: 'Gentle Giant of the Rivers',
    taglinePt: 'Gigante Gentil dos Rios',
    emoji: '🦫',
  },
  {
    id: 'macaw',
    name: 'Arara',
    nameEn: 'Macaw',
    namePt: 'Arara',
    taglineEn: 'Brilliant Wings of Freedom',
    taglinePt: 'Asas Brilhantes da Liberdade',
    emoji: '🦚',
  },
  {
    id: 'sloth',
    name: 'Preguiça',
    nameEn: 'Sloth',
    namePt: 'Preguiça',
    taglineEn: 'Wise Keeper of the Canopy',
    taglinePt: 'Sábio Guardião do Dossel',
    emoji: '🦥',
  },
  {
    id: 'anteater',
    name: 'Tamanduá',
    nameEn: 'Giant Anteater',
    namePt: 'Tamanduá-Bandeira',
    taglineEn: 'Patient Hunter of the Plains',
    taglinePt: 'Caçador Paciente das Planícies',
    emoji: '🐻',
  },
  {
    id: 'tapir',
    name: 'Anta',
    nameEn: 'Tapir',
    namePt: 'Anta',
    taglineEn: 'Ancient Wanderer of the Forest',
    taglinePt: 'Antigo Andarilho da Floresta',
    emoji: '🦏',
  },
  {
    id: 'dolphin',
    name: 'Boto-Cor-de-Rosa',
    nameEn: 'Pink River Dolphin',
    namePt: 'Boto-Cor-de-Rosa',
    taglineEn: 'Mystical Guardian of Waters',
    taglinePt: 'Guardião Místico das Águas',
    emoji: '🐬',
  },
  {
    id: 'monkey',
    name: 'Macaco-Prego',
    nameEn: 'Capuchin Monkey',
    namePt: 'Macaco-Prego',
    taglineEn: 'Clever Acrobat of the Trees',
    taglinePt: 'Acrobata Esperto das Árvores',
    emoji: '🐒',
  },
  {
    id: 'armadillo',
    name: 'Tatu',
    nameEn: 'Armadillo',
    namePt: 'Tatu',
    taglineEn: 'Armored Digger of Secrets',
    taglinePt: 'Escavador Blindado de Segredos',
    emoji: '🦔',
  },
  {
    id: 'ocelot',
    name: 'Jaguatirica',
    nameEn: 'Ocelot',
    namePt: 'Jaguatirica',
    taglineEn: 'Stealthy Shadow of the Night',
    taglinePt: 'Sombra Furtiva da Noite',
    emoji: '🐈',
  },
  {
    id: 'caiman',
    name: 'Jacaré',
    nameEn: 'Caiman',
    namePt: 'Jacaré',
    taglineEn: 'Ancient Ruler of the Swamps',
    taglinePt: 'Antigo Governante dos Pântanos',
    emoji: '🐊',
  },
  {
    id: 'parrot',
    name: 'Papagaio',
    nameEn: 'Parrot',
    namePt: 'Papagaio',
    taglineEn: 'Chatty Messenger of Joy',
    taglinePt: 'Mensageiro Tagarela da Alegria',
    emoji: '🦜',
  },
  {
    id: 'butterfly',
    name: 'Borboleta-Morfo',
    nameEn: 'Blue Morpho Butterfly',
    namePt: 'Borboleta-Morfo-Azul',
    taglineEn: 'Graceful Dancer of the Sky',
    taglinePt: 'Dançarina Graciosa do Céu',
    emoji: '🦋',
  },
  {
    id: 'hawk',
    name: 'Gavião',
    nameEn: 'Hawk',
    namePt: 'Gavião',
    taglineEn: 'Sharp-Eyed Hunter of Heights',
    taglinePt: 'Caçador de Olhar Aguçado das Alturas',
    emoji: '🦅',
  }
];