// Brazilian Fauna Avatars with detailed information

export const BRAZILIAN_FAUNA_AVATARS = [
  {
    id: 'anteater',
    nameEn: 'Giant Anteater',
    namePt: 'Tamanduá-Bandeira',
    taglineEn: 'Patient Hunter of the Plains',
    taglinePt: 'Caçador Paciente das Planícies',
    emoji: '🦡',
    scientificName: 'Myrmecophaga tridactyla',
    habitatEn: 'Savannas, forests, and open fields of Central and South America',
    habitatPt: 'Savanas, florestas e campos abertos da América Central e do Sul',
    characteristicsEn: 'Has a long snout and an extendable tongue used to catch ants and termites. Known for its dense fur and distinctive body stripes.',
    characteristicsPt: 'Possui um focinho longo e uma língua extensível que usa para capturar formigas e cupins. É conhecido por sua pelagem densa e faixas distintivas no corpo.',
    conservationStatusEn: 'Vulnerable',
    conservationStatusPt: 'Vulnerável',
    conservationThreatsEn: 'Habitat loss and hunting',
    conservationThreatsPt: 'Perda de habitat e caça'
  },
  {
    id: 'tapir',
    nameEn: 'Tapir',
    namePt: 'Anta',
    taglineEn: 'Ancient Wanderer of the Forest',
    taglinePt: 'Antigo Andarilho da Floresta',
    emoji: '🦛',
    scientificName: 'Tapirus terrestris',
    habitatEn: 'Tropical forests, savannas, and wetlands of South America',
    habitatPt: 'Florestas tropicais, savanas e áreas alagadas da América do Sul',
    characteristicsEn: 'The largest land mammal in South America, with a flexible snout resembling a small trunk. Has dark fur and a dorsal crest.',
    characteristicsPt: 'É o maior mamífero terrestre da América do Sul, com um focinho flexível que lembra uma pequena tromba. Tem uma pelagem escura e uma crista dorsal.',
    conservationStatusEn: 'Vulnerable',
    conservationStatusPt: 'Vulnerável',
    conservationThreatsEn: 'Habitat destruction and hunting',
    conservationThreatsPt: 'Destruição do habitat e caça'
  },
  {
    id: 'dolphin',
    nameEn: 'Pink River Dolphin',
    namePt: 'Boto-Cor-de-Rosa',
    taglineEn: 'Mystical Guardian of Waters',
    taglinePt: 'Guardião Místico das Águas',
    emoji: '🐬',
    scientificName: 'Inia geoffrensis',
    habitatEn: 'Amazon basin rivers',
    habitatPt: 'Rios da bacia Amazônica',
    characteristicsEn: 'Has a pink coloration that becomes more intense in adult males. Known for its intelligence and ability to swim in shallow waters and among trees during river floods.',
    characteristicsPt: 'Possui uma coloração rosada, que se torna mais intensa nos machos adultos. É conhecido por sua inteligência e habilidade de nadar em águas rasas e entre as árvores durante a cheia dos rios.',
    conservationStatusEn: 'Data Deficient',
    conservationStatusPt: 'Deficiente de dados',
    conservationThreatsEn: 'Habitat destruction and fishing',
    conservationThreatsPt: 'Destruição do habitat e pesca'
  },
  {
    id: 'monkey',
    nameEn: 'Capuchin Monkey',
    namePt: 'Macaco-Prego',
    taglineEn: 'Clever Acrobat of the Trees',
    taglinePt: 'Acrobata Esperto das Árvores',
    emoji: '🐵',
    scientificName: 'Sapajus spp.',
    habitatEn: 'Tropical and subtropical forests of South America',
    habitatPt: 'Florestas tropicais e subtropicais da América do Sul',
    characteristicsEn: 'Known for their intelligence and use of tools. They have dense fur and a prehensile tail.',
    characteristicsPt: 'Conhecidos por sua inteligência e uso de ferramentas. Possuem uma pelagem densa e uma cauda preênsil.',
    conservationStatusEn: 'Varies by species',
    conservationStatusPt: 'Varia conforme a espécie',
    conservationThreatsEn: 'Habitat loss',
    conservationThreatsPt: 'Perda de habitat'
  },
  {
    id: 'armadillo',
    nameEn: 'Armadillo',
    namePt: 'Tatu',
    taglineEn: 'Armored Digger of Secrets',
    taglinePt: 'Escavador Blindado de Segredos',
    emoji: '🦔',
    scientificName: 'Dasypus novemcinctus',
    habitatEn: 'Savannas, forests, and areas near humans in South and Central America',
    habitatPt: 'Savanas, florestas e áreas próximas a humanos na América do Sul e Central',
    characteristicsEn: 'Has a bony shell that protects it. Feeds on insects and small invertebrates.',
    characteristicsPt: 'Possui uma carapaça óssea que o protege. Alimenta-se de insetos e pequenos invertebrados.',
    conservationStatusEn: 'Varies by species',
    conservationStatusPt: 'Varia conforme a espécie',
    conservationThreatsEn: 'Habitat loss',
    conservationThreatsPt: 'Perda de habitat'
  },
  {
    id: 'panther',
    nameEn: 'Black Panther',
    namePt: 'Pantera Negra',
    taglineEn: 'Mysterious Shadow of the Jungle',
    taglinePt: 'Sombra Misteriosa da Selva',
    emoji: '🐈‍⬛',
    scientificName: 'Panthera onca (melanistic)',
    habitatEn: 'Dense tropical forests and rainforests of South and Central America',
    habitatPt: 'Florestas tropicais densas e selvas da América do Sul e Central',
    characteristicsEn: 'A melanistic jaguar with a black coat that still shows faint spots. Known for exceptional stealth, power, and nocturnal hunting abilities.',
    characteristicsPt: 'Uma onça melânica com pelagem preta que ainda mostra manchas sutis. Conhecida por sua furtividade excepcional, força e habilidades de caça noturna.',
    conservationStatusEn: 'Near Threatened',
    conservationStatusPt: 'Quase ameaçado',
    conservationThreatsEn: 'Habitat loss and hunting',
    conservationThreatsPt: 'Perda de habitat e caça'
  },
  {
    id: 'caiman',
    nameEn: 'Caiman',
    namePt: 'Jacaré',
    taglineEn: 'Ancient Ruler of the Swamps',
    taglinePt: 'Antigo Governante dos Pântanos',
    emoji: '🐊',
    scientificName: 'Caiman crocodilus',
    habitatEn: 'Rivers, lakes, and swamps of South America',
    habitatPt: 'Rios, lagos e pântanos da América do Sul',
    characteristicsEn: 'A medium-sized crocodilian with a powerful bite. Has a varied diet including fish, birds, and mammals.',
    characteristicsPt: 'É um crocodiliano de tamanho médio com uma mordida poderosa. Tem uma dieta variada, incluindo peixes, aves e mamíferos.',
    conservationStatusEn: 'Varies by species',
    conservationStatusPt: 'Varia conforme a espécie',
    conservationThreatsEn: 'Habitat loss and hunting',
    conservationThreatsPt: 'Perda de habitat e caça'
  },
  {
    id: 'parrot',
    nameEn: 'Parrot',
    namePt: 'Papagaio',
    taglineEn: 'Chatty Messenger of Joy',
    taglinePt: 'Mensageiro Tagarela da Alegria',
    emoji: '🦜',
    scientificName: 'Amazona aestiva',
    habitatEn: 'Tropical forests, savannas, and urban areas of South America',
    habitatPt: 'Florestas tropicais, savanas e áreas urbanas da América do Sul',
    characteristicsEn: 'Known for their ability to mimic sounds and human speech. They have colorful plumage and a strong, curved beak.',
    characteristicsPt: 'Conhecidos por sua capacidade de imitar sons e fala humana. Possuem plumagem colorida e bico forte e curvo.',
    conservationStatusEn: 'Varies by species',
    conservationStatusPt: 'Varia conforme a espécie',
    conservationThreatsEn: 'Animal trafficking and habitat loss',
    conservationThreatsPt: 'Tráfico de animais e perda de habitat'
  },
  {
    id: 'butterfly',
    nameEn: 'Blue Morpho Butterfly',
    namePt: 'Borboleta-Morfo-Azul',
    taglineEn: 'Graceful Dancer of the Sky',
    taglinePt: 'Dançarina Graciosa do Céu',
    emoji: '🦋',
    scientificName: 'Morpho didius',
    habitatEn: 'Tropical forests of Central and South America',
    habitatPt: 'Florestas tropicais da América Central e do Sul',
    characteristicsEn: 'Has iridescent blue wings visible when in flight, but displays a camouflage pattern when at rest.',
    characteristicsPt: 'Possui asas azuis iridescentes que são visíveis quando em voo, mas apresentam um padrão de camuflagem quando em repouso.',
    conservationStatusEn: 'Not Threatened',
    conservationStatusPt: 'Não ameaçada',
    conservationThreatsEn: 'Habitat destruction',
    conservationThreatsPt: 'Destruição do habitat'
  },
  {
    id: 'hawk',
    nameEn: 'Hawk',
    namePt: 'Gavião',
    taglineEn: 'Sharp-Eyed Hunter of Heights',
    taglinePt: 'Caçador de Olhar Aguçado das Alturas',
    emoji: '🦅',
    scientificName: 'Buteo spp.',
    habitatEn: 'Forests, savannas, and urban areas of South America',
    habitatPt: 'Florestas, savanas e áreas urbanas da América do Sul',
    characteristicsEn: 'Birds of prey with excellent vision, adapted to hunt small mammals, birds, and reptiles.',
    characteristicsPt: 'Aves de rapina com excelente visão, adaptadas para caçar pequenos mamíferos, aves e répteis.',
    conservationStatusEn: 'Varies by species',
    conservationStatusPt: 'Varia conforme a espécie',
    conservationThreatsEn: 'Habitat loss',
    conservationThreatsPt: 'Perda de habitat'
  },
  {
    id: 'jaguar',
    nameEn: 'Jaguar',
    namePt: 'Onça-Pintada',
    taglineEn: 'Fierce Guardian of the Amazon',
    taglinePt: 'Guardião Feroz da Amazônia',
    emoji: '🐆',
    scientificName: 'Panthera onca',
    habitatEn: 'Tropical forests, savannas, and swamps of South and Central America',
    habitatPt: 'Florestas tropicais, savanas e pântanos da América do Sul e Central',
    characteristicsEn: 'The largest feline in the Americas, known for its yellow coat with black spots and exceptional strength.',
    characteristicsPt: 'É o maior felino das Américas, conhecido por sua pelagem amarela com manchas pretas e sua força excepcional.',
    conservationStatusEn: 'Near Threatened',
    conservationStatusPt: 'Quase ameaçado',
    conservationThreatsEn: 'Habitat loss and hunting',
    conservationThreatsPt: 'Perda de habitat e caça'
  },
  {
    id: 'toucan',
    nameEn: 'Toucan',
    namePt: 'Tucano',
    taglineEn: 'Colorful Spirit of the Rainforest',
    taglinePt: 'Espírito Colorido da Floresta',
    emoji: '🦜',
    scientificName: 'Ramphastos toco',
    habitatEn: 'Tropical forests of South America',
    habitatPt: 'Florestas tropicais da América do Sul',
    characteristicsEn: 'Known for their large, colorful beak. They feed on fruits, insects, and small vertebrates.',
    characteristicsPt: 'Conhecidos por seu bico grande e colorido. Alimentam-se de frutos, insetos e pequenos vertebrados.',
    conservationStatusEn: 'Varies by species',
    conservationStatusPt: 'Varia conforme a espécie',
    conservationThreatsEn: 'Habitat loss',
    conservationThreatsPt: 'Perda de habitat'
  },
  {
    id: 'capybara',
    nameEn: 'Capybara',
    namePt: 'Capivara',
    taglineEn: 'Gentle Giant of the Rivers',
    taglinePt: 'Gigante Gentil dos Rios',
    emoji: '🦫',
    scientificName: 'Hydrochoerus hydrochaeris',
    habitatEn: 'Wetlands, savannas, and forests near water bodies in South America',
    habitatPt: 'Áreas alagadas, savanas e florestas próximas a corpos d\'água na América do Sul',
    characteristicsEn: 'The largest rodent in the world, with thick fur and no tail. Semi-aquatic and lives in social groups.',
    characteristicsPt: 'É o maior roedor do mundo, com uma pelagem espessa e sem cauda. É semi-aquático e vive em grupos sociais.',
    conservationStatusEn: 'Not Threatened',
    conservationStatusPt: 'Não ameaçada',
    conservationThreatsEn: 'Regional threats in some areas',
    conservationThreatsPt: 'Ameaças em algumas regiões'
  },
  {
    id: 'macaw',
    nameEn: 'Macaw',
    namePt: 'Arara',
    taglineEn: 'Brilliant Wings of Freedom',
    taglinePt: 'Asas Brilhantes da Liberdade',
    emoji: '🦜',
    scientificName: 'Ara ararauna',
    habitatEn: 'Tropical forests and savannas of South America',
    habitatPt: 'Florestas tropicais e savanas da América do Sul',
    characteristicsEn: 'Large birds with vibrant plumage, known for their intelligence and complex vocalizations.',
    characteristicsPt: 'Aves de grande porte com plumagem vibrante, conhecidas por sua inteligência e vocalizações complexas.',
    conservationStatusEn: 'Varies by species',
    conservationStatusPt: 'Varia conforme a espécie',
    conservationThreatsEn: 'Animal trafficking and habitat loss',
    conservationThreatsPt: 'Tráfico de animais e perda de habitat'
  },
  {
    id: 'sloth',
    nameEn: 'Sloth',
    namePt: 'Preguiça',
    taglineEn: 'Wise Keeper of the Canopy',
    taglinePt: 'Sábio Guardião do Dossel',
    emoji: '🦥',
    scientificName: 'Bradypus variegatus',
    habitatEn: 'Tropical forests of South and Central America',
    habitatPt: 'Florestas tropicais da América do Sul e Central',
    characteristicsEn: 'Arboreal mammals known for their slow movement and fur that harbors algae, giving them a greenish color.',
    characteristicsPt: 'Mamíferos arbóreos conhecidos por seu movimento lento e sua pelagem que abriga algas, dando-lhe uma coloração esverdeada.',
    conservationStatusEn: 'Varies by species',
    conservationStatusPt: 'Varia conforme a espécie',
    conservationThreatsEn: 'Habitat loss',
    conservationThreatsPt: 'Perda de habitat'
  }
];